def get_strings(lang: str) -> dict:
    fa = {
        "app_title": "نرم‌افزار حسابداری و فاکتور",
        "tab_dashboard": "داشبورد",
        "tab_company": "اطلاعات شرکت",
        "tab_customers": "مشتریان",
        "tab_products": "کالاها",
        "tab_invoice": "صدور فاکتور",
        "tab_reports": "گزارش‌ها",
        "tab_settings": "تنظیمات",
        "company_name_fa": "نام شرکت (فارسی)",
        "company_name_en": "نام شرکت (انگلیسی)",
        "company_phone": "تلفن",
        "company_address_fa": "آدرس (فارسی)",
        "company_address_en": "آدرس (انگلیسی)",
        "save": "ذخیره",
        "add": "افزودن",
        "edit": "ویرایش",
        "delete": "حذف",
        "name": "نام",
        "phone": "تلفن",
        "address": "آدرس",
        "product": "کالا",
        "price": "قیمت واحد",
        "quantity": "تعداد",
        "discount": "تخفیف ٪",
        "tax": "مالیات ٪",
        "total": "مبلغ",
        "customer": "مشتری",
        "date": "تاریخ",
        "add_row": "افزودن ردیف",
        "remove_row": "حذف ردیف",
        "save_invoice": "ثبت فاکتور",
        "subtotal": "جمع جزء",
        "discount_sum": "جمع تخفیف",
        "taxable": "مبلغ مشمول",
        "vat": "مالیات",
        "grand_total": "جمع کل",
        "export_csv": "خروجی CSV",
        "lang_label": "زبان رابط",
        "lang_fa": "فارسی",
        "lang_en": "English",
        "db_type": "نوع پایگاه‌داده",
        "db_sqlite": "SQLite (پیش‌فرض)",
        "db_access": "Microsoft Access",
        "status_ready": "آماده.",
        "msg_saved": "ذخیره شد.",
        "msg_error": "خطا",
        "msg_need_customer_product": "ابتدا مشتری و کالا ثبت کنید.",
        "invoice_no": "شماره فاکتور",
        "customer_name": "نام مشتری",
        "report_refresh": "بروزرسانی گزارش",
    }
    en = {
        "app_title": "Accounting & Invoicing",
        "tab_dashboard": "Dashboard",
        "tab_company": "Company",
        "tab_customers": "Customers",
        "tab_products": "Products",
        "tab_invoice": "Invoice",
        "tab_reports": "Reports",
        "tab_settings": "Settings",
        "company_name_fa": "Company Name (FA)",
        "company_name_en": "Company Name (EN)",
        "company_phone": "Phone",
        "company_address_fa": "Address (FA)",
        "company_address_en": "Address (EN)",
        "save": "Save",
        "add": "Add",
        "edit": "Edit",
        "delete": "Delete",
        "name": "Name",
        "phone": "Phone",
        "address": "Address",
        "product": "Product",
        "price": "Unit Price",
        "quantity": "Qty",
        "discount": "Discount %",
        "tax": "Tax %",
        "total": "Total",
        "customer": "Customer",
        "date": "Date",
        "add_row": "Add Row",
        "remove_row": "Remove Row",
        "save_invoice": "Save Invoice",
        "subtotal": "Subtotal",
        "discount_sum": "Discount",
        "taxable": "Taxable",
        "vat": "VAT",
        "grand_total": "Grand Total",
        "export_csv": "Export CSV",
        "lang_label": "UI Language",
        "lang_fa": "Persian",
        "lang_en": "English",
        "db_type": "Database Type",
        "db_sqlite": "SQLite (default)",
        "db_access": "Microsoft Access",
        "status_ready": "Ready.",
        "msg_saved": "Saved.",
        "msg_error": "Error",
        "msg_need_customer_product": "Please add at least one customer and one product first.",
        "invoice_no": "Invoice No.",
        "customer_name": "Customer Name",
        "report_refresh": "Refresh",
    }
    return fa if lang.lower() == "fa" else en
